import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hellow Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <header>This is the header</header>
        {children}
      </body>
    </html>
  );
}
